<?php
$form = $this->form;
$email = $form->get('email');
$email->setAttribute('placeholder', $this->translate('loginForm.email.placeholder'));
$email->setLabel($this->translate('loginForm.email.label'));
?>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('forgotPassword.heading')?></h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="">
                        <div class="form-group">
                            <?php echo $this->formLabel($email) ?>
                            <div class="col-sm-9">
                                <?php echo $this->formInput($email) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <?php echo $this->formSubmit($this->form->get('submit')) ?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>